#!/usr/bin/env bash
#-*- mode: sh; -*-
########################################################################
# configure for local Docker development
########################################################################
#   DBI_PASS=password ./build-local 
#   cd docker
#   docker-compose up


########################################################################
# Note: The MySQL hostname locally is taken from
# `COMPOSE_PROJECT_NAME` so we are going to assume that you want the
# database hostname to be the same as your API's name...ymmv
########################################################################

API_NAME=bedrock-api
MYSQL_HOST=${API_NAME}_db_1
MYSQL_USER=fred
MYSQL_DATABASE=example

# DOMAIN is only use to set cross-site headers
DOMAIN=treasurersbriefcase.com

./configure \
  --with-mysql-host=$MYSQL_HOST \
  --with-mysql-user=$MYSQL_USER \
  --with-mysql-database=$MYSQL_DATABASE \
  --with-api-name=$API_NAME \
  --with-domain=$DOMAIN \
  --with-mysql-password="$DBI_PASS"

test -z "$DBI_PASS" && echo -e "\nYou probably forgot to set a MySQL password?\n\nDBI_PASS=foo ./build-local"

