#!/usr/bin/env bash
#-*- mode: sh; -*-
# configure an ECS HTTP API
#

########################################################################
get_group_id() {
########################################################################
    aws ec2 describe-security-groups --profile $AWS_PROFILE \
        --filters Name=group-name,Values="$1" | jq -r '.SecurityGroups[]|.GroupId' 
}

########################################################################
get_subnet_id() {
########################################################################
    aws ec2 describe-subnets --profile $AWS_PROFILE \
        --filter=Name=tag:Name,Values=$1 | jq -r '.Subnets[]|.SubnetId'
}

########################################################################
get_hosted_zone() {
########################################################################
    aws route53 list-hosted-zones --profile $AWS_ROUTE53_PROFILE \
        | jq -r '.HostedZones[] | select(.Name=="'$DOMAIN'." and .Config.PrivateZone) | .Id'

}

API_NAME=example-api
DOMAIN=treasurersbriefcase.com
AWS_PROFILE=sandbox
AWS_ROUTE53_PROFILE=prod
SUBNET=$(get_subnet_id 'Private-1')
MYSQL_SECURITY_GROUP=$(get_group_id mysql-security-group);
SECURITY_GROUP=$(get_group_id 'internal web server')
HOSTED_ZONE_ID=$(get_hosted_zone)
HOSTED_ZONE_ID=$(basename $HOSTED_ZONE_ID)

AWS_ROUTE53_PROFILE=prod
CLUSTER_NAME=fargate-cluster
HOST=sandbox-api.$DOMAIN
ALB_NAME=internal

./configure \
  --with-mysql-host=mysql.local \
  --with-mysql-user=fred \
  --with-mysql-database=example \
  --with-aws-profile=$AWS_PROFILE \
  --with-aws-route53-profile=$AWS_ROUTE53_PROFILE \
  --with-aws-cluster-name=$CLUSTER_NAME \
  --with-aws-security-group=$SECURITY_GROUP \
  --with-aws-subnets=$SUBNET \
  --enable-alb \
  --enable-aws \
  --enable-autoscaling \
  --enable-route53 \
  --with-aws-alb-name=$ALB_NAME \
  --with-api-host=$HOST \
  --with-api-name=$API_NAME \
  --with-domain=$DOMAIN \
  --with-aws-hosted-zone-id=$HOSTED_ZONE_ID \
  --with-aws-mysql-security-group=$MYSQL_SECURITY_GROUP \

