#!/usr/bin/env bash
#-*- mode: sh; -*-

# configure with --disable-database to prevent default assignment of a root password
if test -n "$MYSQL_ROOT_PASSWORD"; then

    until mysql -h $MYSQL_HOST -u root --password="$MYSQL_ROOT_PASSWORD" -e "SELECT 1" >/dev/null; do
        echo "Waiting for MySQL to be ready..."
        sleep 2
    done

    if test -e /usr/local/share/setup.sql; then
        mysql -h $MYSQL_HOST -u root -p"$MYSQL_ROOT_PASSWORD" < /usr/local/share/setup.sql
    fi

    SESSION_CONFIG=/var/www/bedrock/config.d/startup/mysql-session.xml
    if test -e $SESSION_CONFIG; then
        dnky-config -r -i /var/www/bedrock/config.d/startup/mysql-session.xml  \
                    config.password "$MYSQL_PASSWORD" \
                    config.host "$MYSQL_HOST"
    fi
fi

API_CONFIG="/var/www/bedrock/config/$API_NAME.xml"
if test -e $API_CONFIG; then
    dnky-config -r -i /var/www/bedrock/config/$API_NAME.xml \
                DBI_PASS "$MYSQL_PASSWORD" \
                DBI_HOST "$MYSQL_HOST" \
                API_KEY "$API_KEY"
fi

source /etc/apache2/envvars

/usr/sbin/apache2 -k start -D FOREGROUND
